POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Async/Await Explained Clearly",
  "author": "Emily Davis",
  "url": "https://example.com/async-await",
  "likes": 15
}
###

GET http://localhost:3003/api/blogs
###

