POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "MongoDB vs SQL: Key Differences",
  "author": "Michael Brown",
  "url": "https://example.com/mongodb-vs-sql",
  "likes": 20
}
###

GET http://localhost:3003/api/blogs
###

